### ISSUE TITLE
AttributeError: type object 'MetadataType' has no attribute 'MOVIE'

### ISSUE THREAD

**Issue by barraIhsan** [mov-cli/mov-cli-files#3]
When trying to play a media, this occur
![image](https://github.com/mov-cli/mov-cli-files/assets/57800056/8cb8f280-1dde-4c13-be45-b359bc105c53)
<details>
<summary>Full log</summary>
<pre>
[INFO] (mov_cli) - Using 'files.DEFAULT' scraper...
[INFO] (mov_cli) - Searching for 'shikanoko'...
Traceback (most recent call last):
  File "/usr/sbin/mov-cli", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 167, in app
    uwu_app()
  File "/usr/lib/python3.12/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/lib/python3.12/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/typer/core.py", line 716, in main
    return _main(
           ^^^^^^
  File "/usr/lib/python3.12/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 124, in mov_cli
    choice = search(query, auto_select, chosen_scraper, config.fzf_enabled, config.preview, config.limit)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mov_cli/cli/search.py", line 46, in search
    choice = prompt(
             ^^^^^^^
  File "/usr/lib/python3.12/site-packages/mov_cli/cli/ui.py", line 87, in prompt
    is_just_one, choices = is_it_just_one_choice(choices)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mov_cli/cli/ui.py", line 59, in is_it_just_one_choice
    for index, _ in enumerate(choices):
  File "/usr/lib/python3.12/site-packages/mov_cli/cli/search.py", line 48, in <genexpr>
    choices = (choice for choice in search_results),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mov_cli_files/scraper.py", line 60, in search
    type = MetadataType.MOVIE,
           ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'MetadataType' has no attribute 'MOVIE'
</pre>
</details>

Python: `3.12.4`

**Comment by ananasmoe** [comment]
Are you sure you are using the latest version: v1.1.1?

**Comment by barraIhsan** [comment]
ahh, you updated it. I confused when on aur it says 1.1.1. Lemme try it

**Comment by barraIhsan** [comment]
it works! thanks
